### ISSUE TITLE
Default image

### ISSUE THREAD

**Issue by victorpantoja** [pitomba/spriter#5]
Wouldn't be great if we could tell pitomba to use a default image when a imagem were not found?

**Comment by romulojales** [comment]
I think this feature is user responsible by control if an image exists or not. But, I implemented so forth...

Resolved: https://github.com/pitomba/pitomba/commit/f0e3d36737f2f03c1081ca316ea2477f30a73689

Now, default_path is an argument to image's path in the Sprite initial arguments. The default value is empty string (a.k ""). 
If empty string, spriter will ignore the default image and follows without fault recovery.
If not, Spriter will try to load the image and use it as fault recovery image whenever a path in paths list argument does not exists.
The CSS class name of the faulty image is prefixed with the original basename - as normal way - but the background-position is address to default image position.
