### ISSUE TITLE
Quality Review

### ISSUE THREAD

**Issue by romulojales** [pitomba/spriter#8]
The Pitomba's project covers only the sprite.py file with 95% of coverage. The file watch.py isn't test. We need improve the project coverage to 100% of files and line

Another quality point is the pep8 directives: It have 9 violations.

**Comment by kplaube** [comment]
We can use Coveralls (https://coveralls.io/) and Codeq (https://codeq.io/) to always remind us about these.

**Comment by romulojales** [comment]
Very nice! I see the Coveralls have badge of coverage percent! I can't evaluate codeq, I get 404 status. Is Codeq a reliable tool? What's the difference between them?

**Comment by victorpantoja** [comment]
I'm improving Klaus' test cases right now.
