### ISSUE TITLE
Watchdog Egg

### ISSUE THREAD

**Issue by romulojales** [pitomba/spriter#9]
The pitomba originally was designed for work as a watchdog sprite generator. We need split the command from the library on the project structure and egg generator

**Comment by kplaube** [comment]
Why can't we just use an approach like Django does? Add a "binary" script (like django-admin.py), with the proper help and instructions of use, to do this action.
So, we can use Spriter as a lib and as a tool, with only one egg. What do you think?

**Comment by romulojales** [comment]
Sounds good.
I'm waiting for your commit.

**Comment by victorpantoja** [comment]
As we talked, I'll implement this feature in setup.py file.

**Comment by victorpantoja** [comment]
Also, I'll update pitomba's docs.

**Comment by victorpantoja** [comment]
Done. Usage:

spriter-watcher.py -c /path/to/config/file
